on: [push]
name: build

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: node:10.18-jessie
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install SQLX
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: sqlx-cli --features openssl-vendored
      - name: Save sqlx artifact
        uses: actions/upload-artifact@v2
        with:
          name: sqlx-${{ github.sha }}
          path: ~/.cargo/bin/sqlx
          retention-days: 1
      - name: Setup database
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/runs_ci
        run: sqlx database setup
      - name: Build
        uses: actions-rs/cargo@v1
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres/runs_ci
        with:
          command: build
          args: --release
      - name: Save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.workflow }}-${{ github.sha }}
          path: ${{ github.workspace }}/target/release/runs-api
          retention-days: 1
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    needs: build
    if: startsWith(github.event.head_commit.message, 'deploy:')
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-${{ github.sha }}
          path: "~"
      - name: Download sqlx
        uses: actions/download-artifact@v2
        with:
          name: sqlx-${{ github.sha }}
          path: "~"
      - name: Run SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MACHINE_SSH_KEY }}
      - name: Add server to known hosts
        run: mkdir -p ~/.ssh; ssh-keyscan -p ${{ secrets.MACHINE_SSH_PORT }} ${{ secrets.MACHINE_HOST }} >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy migrations to server
        run: scp -P ${{ secrets.MACHINE_SSH_PORT }} -r ${{ github.workspace }}/migrations runs@${{ secrets.MACHINE_HOST }}:~/api
      - name: Copy sqlx to server
        run: scp -P ${{ secrets.MACHINE_SSH_PORT }} ~/sqlx runs@${{ secrets.MACHINE_HOST }}:~/api/bin; ssh -p ${{ secrets.MACHINE_SSH_PORT }} runs@${{ secrets.MACHINE_HOST }} "chmod +x ~/api/bin/sqlx"
      - name: Stop Runs-API
        run: ssh -p ${{ secrets.MACHINE_SSH_PORT }} runs@${{ secrets.MACHINE_HOST }} "sudo systemctl stop runs-api"
      - name: Copy binary to server
        run: scp -P ${{ secrets.MACHINE_SSH_PORT }} ~/runs-api runs@${{ secrets.MACHINE_HOST }}:~/api/bin; ssh -p ${{ secrets.MACHINE_SSH_PORT }} runs@${{ secrets.MACHINE_HOST }} "chmod +x ~/api/bin/runs-api"
      - name: Run migrations
        run: ssh -p ${{ secrets.MACHINE_SSH_PORT }} runs@${{ secrets.MACHINE_HOST }} "pushd ~/api; source ~/.profile; bin/sqlx database setup"
      - name: Start Runs-API
        run: ssh -p ${{ secrets.MACHINE_SSH_PORT }} runs@${{ secrets.MACHINE_HOST }} "sudo systemctl start runs-api"
