on: [workflow_dispatch]
name: deploy

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build-${{ github.sha }}
      - name: Rename build
        run: mv build-${{ github.sha }} runs-api
      - name: Run SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MACHINE_SSH_KEY }}
      - name: Copy to server
        run: scp -p ${{ secrets.MACHINE_SSH_PORT }} runs-api runs@${{ secrets.MACHINE_HOST }}:/opt/runs/api/bin
